<?php

namespace Avalanche\Bundle\ImagineBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImagineController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Avalanche\Bundle\ImagineBundle\Controller\ImagineController();
        return $instance;
    }
}
