_api_create:
    pattern: /api/v1/product/
    defaults: { _controller: PriaProductBundle:CRUD:create, _format: json }
    requirements:
        _method: POST

_api_fetch:
    pattern: /api/v1/product/{id}
    defaults: {_controller: PriaProductBundle:CRUD:fetch, _format: json }
    requirements:
        _method: GET

_api_fetchAll:
    pattern: /api/v1/product/
    defaults: {_controller: PriaProductBundle:CRUD:fetchAll, _format: json }
    requirements:
        _method: GET

#_api_patch:
#    pattern: /api/v1/product/{id}
#    defaults: { _controller: PriaProductBundle:CRUD:patch, _format: json }
#    requirements:
#        _method: PATCH

_api_update:
    pattern: /api/v1/product/{id}
    defaults: { _controller: PriaProductBundle:CRUD:update, _format: json }
    requirements:
        _method: PUT

_api_delete:
    pattern: /api/v1/product/{id}
    defaults: { _controller: PriaProductBundle:CRUD:delete, _format: json }
    requirements:
        _method: DELETE
