security:
  encoders:
       Pria\ProfileBundle\Entity\User:
           algorithm:        sha1
           encode_as_base64: false
           iterations:       1

  providers:
        main:
          entity: { class: Pria\ProfileBundle\Entity\User, property: username}

  firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
          anonymous: ~
      secured_area:
          pattern:    ^/oauth/
          form_login:
              require_previous_session: false
              check_path: login_check
              success_handler: pria.authentication_handler
              failure_handler: pria.authentication_handler
          logout:
              path:   logout
              success_handler: pria.logout_success_handler
          http_basic:
              realm: "Secured Logged Area"
      admin_area:
           pattern:    ^/oauth/admin/
           http_basic:
                realm: "Secured Admin Area"
      user_area:
           pattern:    ^/oauth/user/
           http_basic:
                realm: "Secured User Area"

  access_control:
        - { path: ^/oauth/admin/,  roles: ROLE_ADMIN }
        - { path: ^/oauth/user/,   roles: ROLE_USER  }

  role_hierarchy:
      ROLE_ADMIN: ROLE_ADMIN
      ROLE_USER: ROLE_USER
